import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Navbar from "@/components/Navbar/Navbar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        // ${geistSans.variable} ${geistMono.variable}
        //   <div className="absolute inset-0 z-[-1] ">
        //   <Image className=" w-full mask-inner mask-outer" src="/bg/circle.jpg" alt=""  fill={true} objectFit="contain" />
        // </div>
        <html lang="en">
            <body className={` antialiased h-dvh  test `}>
                <div className=" h-[calc(100%-100px)]">{children}</div>
                    <div className="h-[100px]">
                        <Navbar />
                    </div>
            </body>
        </html>
    );
}
