
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Css` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Css
 * 
 */
export type CssModel = runtime.Types.Result.DefaultSelection<Prisma.$CssPayload>

export type AggregateCss = {
  _count: CssCountAggregateOutputType | null
  _avg: CssAvgAggregateOutputType | null
  _sum: CssSumAggregateOutputType | null
  _min: CssMinAggregateOutputType | null
  _max: CssMaxAggregateOutputType | null
}

export type CssAvgAggregateOutputType = {
  id: number | null
}

export type CssSumAggregateOutputType = {
  id: number | null
}

export type CssMinAggregateOutputType = {
  id: number | null
  key: string | null
  content: string | null
}

export type CssMaxAggregateOutputType = {
  id: number | null
  key: string | null
  content: string | null
}

export type CssCountAggregateOutputType = {
  id: number
  key: number
  content: number
  _all: number
}


export type CssAvgAggregateInputType = {
  id?: true
}

export type CssSumAggregateInputType = {
  id?: true
}

export type CssMinAggregateInputType = {
  id?: true
  key?: true
  content?: true
}

export type CssMaxAggregateInputType = {
  id?: true
  key?: true
  content?: true
}

export type CssCountAggregateInputType = {
  id?: true
  key?: true
  content?: true
  _all?: true
}

export type CssAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Css to aggregate.
   */
  where?: Prisma.CssWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Csses to fetch.
   */
  orderBy?: Prisma.CssOrderByWithRelationInput | Prisma.CssOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CssWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Csses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Csses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Csses
  **/
  _count?: true | CssCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CssAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CssSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CssMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CssMaxAggregateInputType
}

export type GetCssAggregateType<T extends CssAggregateArgs> = {
      [P in keyof T & keyof AggregateCss]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCss[P]>
    : Prisma.GetScalarType<T[P], AggregateCss[P]>
}




export type CssGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CssWhereInput
  orderBy?: Prisma.CssOrderByWithAggregationInput | Prisma.CssOrderByWithAggregationInput[]
  by: Prisma.CssScalarFieldEnum[] | Prisma.CssScalarFieldEnum
  having?: Prisma.CssScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CssCountAggregateInputType | true
  _avg?: CssAvgAggregateInputType
  _sum?: CssSumAggregateInputType
  _min?: CssMinAggregateInputType
  _max?: CssMaxAggregateInputType
}

export type CssGroupByOutputType = {
  id: number
  key: string
  content: string
  _count: CssCountAggregateOutputType | null
  _avg: CssAvgAggregateOutputType | null
  _sum: CssSumAggregateOutputType | null
  _min: CssMinAggregateOutputType | null
  _max: CssMaxAggregateOutputType | null
}

type GetCssGroupByPayload<T extends CssGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CssGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CssGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CssGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CssGroupByOutputType[P]>
      }
    >
  >



export type CssWhereInput = {
  AND?: Prisma.CssWhereInput | Prisma.CssWhereInput[]
  OR?: Prisma.CssWhereInput[]
  NOT?: Prisma.CssWhereInput | Prisma.CssWhereInput[]
  id?: Prisma.IntFilter<"Css"> | number
  key?: Prisma.StringFilter<"Css"> | string
  content?: Prisma.StringFilter<"Css"> | string
}

export type CssOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  content?: Prisma.SortOrder
}

export type CssWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  key?: string
  AND?: Prisma.CssWhereInput | Prisma.CssWhereInput[]
  OR?: Prisma.CssWhereInput[]
  NOT?: Prisma.CssWhereInput | Prisma.CssWhereInput[]
  content?: Prisma.StringFilter<"Css"> | string
}, "id" | "key">

export type CssOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  content?: Prisma.SortOrder
  _count?: Prisma.CssCountOrderByAggregateInput
  _avg?: Prisma.CssAvgOrderByAggregateInput
  _max?: Prisma.CssMaxOrderByAggregateInput
  _min?: Prisma.CssMinOrderByAggregateInput
  _sum?: Prisma.CssSumOrderByAggregateInput
}

export type CssScalarWhereWithAggregatesInput = {
  AND?: Prisma.CssScalarWhereWithAggregatesInput | Prisma.CssScalarWhereWithAggregatesInput[]
  OR?: Prisma.CssScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CssScalarWhereWithAggregatesInput | Prisma.CssScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Css"> | number
  key?: Prisma.StringWithAggregatesFilter<"Css"> | string
  content?: Prisma.StringWithAggregatesFilter<"Css"> | string
}

export type CssCreateInput = {
  key: string
  content: string
}

export type CssUncheckedCreateInput = {
  id?: number
  key: string
  content: string
}

export type CssUpdateInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CssUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  key?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CssCreateManyInput = {
  id?: number
  key: string
  content: string
}

export type CssUpdateManyMutationInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CssUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  key?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CssCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  content?: Prisma.SortOrder
}

export type CssAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type CssMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  content?: Prisma.SortOrder
}

export type CssMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  content?: Prisma.SortOrder
}

export type CssSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}



export type CssSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  key?: boolean
  content?: boolean
}, ExtArgs["result"]["css"]>

export type CssSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  key?: boolean
  content?: boolean
}, ExtArgs["result"]["css"]>

export type CssSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  key?: boolean
  content?: boolean
}, ExtArgs["result"]["css"]>

export type CssSelectScalar = {
  id?: boolean
  key?: boolean
  content?: boolean
}

export type CssOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "key" | "content", ExtArgs["result"]["css"]>

export type $CssPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Css"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    key: string
    content: string
  }, ExtArgs["result"]["css"]>
  composites: {}
}

export type CssGetPayload<S extends boolean | null | undefined | CssDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CssPayload, S>

export type CssCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CssFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CssCountAggregateInputType | true
  }

export interface CssDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Css'], meta: { name: 'Css' } }
  /**
   * Find zero or one Css that matches the filter.
   * @param {CssFindUniqueArgs} args - Arguments to find a Css
   * @example
   * // Get one Css
   * const css = await prisma.css.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CssFindUniqueArgs>(args: Prisma.SelectSubset<T, CssFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CssClient<runtime.Types.Result.GetResult<Prisma.$CssPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Css that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CssFindUniqueOrThrowArgs} args - Arguments to find a Css
   * @example
   * // Get one Css
   * const css = await prisma.css.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CssFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CssFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CssClient<runtime.Types.Result.GetResult<Prisma.$CssPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Css that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CssFindFirstArgs} args - Arguments to find a Css
   * @example
   * // Get one Css
   * const css = await prisma.css.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CssFindFirstArgs>(args?: Prisma.SelectSubset<T, CssFindFirstArgs<ExtArgs>>): Prisma.Prisma__CssClient<runtime.Types.Result.GetResult<Prisma.$CssPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Css that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CssFindFirstOrThrowArgs} args - Arguments to find a Css
   * @example
   * // Get one Css
   * const css = await prisma.css.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CssFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CssFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CssClient<runtime.Types.Result.GetResult<Prisma.$CssPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Csses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CssFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Csses
   * const csses = await prisma.css.findMany()
   * 
   * // Get first 10 Csses
   * const csses = await prisma.css.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const cssWithIdOnly = await prisma.css.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CssFindManyArgs>(args?: Prisma.SelectSubset<T, CssFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CssPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Css.
   * @param {CssCreateArgs} args - Arguments to create a Css.
   * @example
   * // Create one Css
   * const Css = await prisma.css.create({
   *   data: {
   *     // ... data to create a Css
   *   }
   * })
   * 
   */
  create<T extends CssCreateArgs>(args: Prisma.SelectSubset<T, CssCreateArgs<ExtArgs>>): Prisma.Prisma__CssClient<runtime.Types.Result.GetResult<Prisma.$CssPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Csses.
   * @param {CssCreateManyArgs} args - Arguments to create many Csses.
   * @example
   * // Create many Csses
   * const css = await prisma.css.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CssCreateManyArgs>(args?: Prisma.SelectSubset<T, CssCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Csses and returns the data saved in the database.
   * @param {CssCreateManyAndReturnArgs} args - Arguments to create many Csses.
   * @example
   * // Create many Csses
   * const css = await prisma.css.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Csses and only return the `id`
   * const cssWithIdOnly = await prisma.css.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CssCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CssCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CssPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Css.
   * @param {CssDeleteArgs} args - Arguments to delete one Css.
   * @example
   * // Delete one Css
   * const Css = await prisma.css.delete({
   *   where: {
   *     // ... filter to delete one Css
   *   }
   * })
   * 
   */
  delete<T extends CssDeleteArgs>(args: Prisma.SelectSubset<T, CssDeleteArgs<ExtArgs>>): Prisma.Prisma__CssClient<runtime.Types.Result.GetResult<Prisma.$CssPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Css.
   * @param {CssUpdateArgs} args - Arguments to update one Css.
   * @example
   * // Update one Css
   * const css = await prisma.css.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CssUpdateArgs>(args: Prisma.SelectSubset<T, CssUpdateArgs<ExtArgs>>): Prisma.Prisma__CssClient<runtime.Types.Result.GetResult<Prisma.$CssPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Csses.
   * @param {CssDeleteManyArgs} args - Arguments to filter Csses to delete.
   * @example
   * // Delete a few Csses
   * const { count } = await prisma.css.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CssDeleteManyArgs>(args?: Prisma.SelectSubset<T, CssDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Csses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CssUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Csses
   * const css = await prisma.css.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CssUpdateManyArgs>(args: Prisma.SelectSubset<T, CssUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Csses and returns the data updated in the database.
   * @param {CssUpdateManyAndReturnArgs} args - Arguments to update many Csses.
   * @example
   * // Update many Csses
   * const css = await prisma.css.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Csses and only return the `id`
   * const cssWithIdOnly = await prisma.css.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CssUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CssUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CssPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Css.
   * @param {CssUpsertArgs} args - Arguments to update or create a Css.
   * @example
   * // Update or create a Css
   * const css = await prisma.css.upsert({
   *   create: {
   *     // ... data to create a Css
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Css we want to update
   *   }
   * })
   */
  upsert<T extends CssUpsertArgs>(args: Prisma.SelectSubset<T, CssUpsertArgs<ExtArgs>>): Prisma.Prisma__CssClient<runtime.Types.Result.GetResult<Prisma.$CssPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Csses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CssCountArgs} args - Arguments to filter Csses to count.
   * @example
   * // Count the number of Csses
   * const count = await prisma.css.count({
   *   where: {
   *     // ... the filter for the Csses we want to count
   *   }
   * })
  **/
  count<T extends CssCountArgs>(
    args?: Prisma.Subset<T, CssCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CssCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Css.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CssAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CssAggregateArgs>(args: Prisma.Subset<T, CssAggregateArgs>): Prisma.PrismaPromise<GetCssAggregateType<T>>

  /**
   * Group by Css.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CssGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CssGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CssGroupByArgs['orderBy'] }
      : { orderBy?: CssGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CssGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCssGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Css model
 */
readonly fields: CssFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Css.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CssClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Css model
 */
export interface CssFieldRefs {
  readonly id: Prisma.FieldRef<"Css", 'Int'>
  readonly key: Prisma.FieldRef<"Css", 'String'>
  readonly content: Prisma.FieldRef<"Css", 'String'>
}
    

// Custom InputTypes
/**
 * Css findUnique
 */
export type CssFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Css
   */
  select?: Prisma.CssSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Css
   */
  omit?: Prisma.CssOmit<ExtArgs> | null
  /**
   * Filter, which Css to fetch.
   */
  where: Prisma.CssWhereUniqueInput
}

/**
 * Css findUniqueOrThrow
 */
export type CssFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Css
   */
  select?: Prisma.CssSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Css
   */
  omit?: Prisma.CssOmit<ExtArgs> | null
  /**
   * Filter, which Css to fetch.
   */
  where: Prisma.CssWhereUniqueInput
}

/**
 * Css findFirst
 */
export type CssFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Css
   */
  select?: Prisma.CssSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Css
   */
  omit?: Prisma.CssOmit<ExtArgs> | null
  /**
   * Filter, which Css to fetch.
   */
  where?: Prisma.CssWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Csses to fetch.
   */
  orderBy?: Prisma.CssOrderByWithRelationInput | Prisma.CssOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Csses.
   */
  cursor?: Prisma.CssWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Csses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Csses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Csses.
   */
  distinct?: Prisma.CssScalarFieldEnum | Prisma.CssScalarFieldEnum[]
}

/**
 * Css findFirstOrThrow
 */
export type CssFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Css
   */
  select?: Prisma.CssSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Css
   */
  omit?: Prisma.CssOmit<ExtArgs> | null
  /**
   * Filter, which Css to fetch.
   */
  where?: Prisma.CssWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Csses to fetch.
   */
  orderBy?: Prisma.CssOrderByWithRelationInput | Prisma.CssOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Csses.
   */
  cursor?: Prisma.CssWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Csses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Csses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Csses.
   */
  distinct?: Prisma.CssScalarFieldEnum | Prisma.CssScalarFieldEnum[]
}

/**
 * Css findMany
 */
export type CssFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Css
   */
  select?: Prisma.CssSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Css
   */
  omit?: Prisma.CssOmit<ExtArgs> | null
  /**
   * Filter, which Csses to fetch.
   */
  where?: Prisma.CssWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Csses to fetch.
   */
  orderBy?: Prisma.CssOrderByWithRelationInput | Prisma.CssOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Csses.
   */
  cursor?: Prisma.CssWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Csses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Csses.
   */
  skip?: number
  distinct?: Prisma.CssScalarFieldEnum | Prisma.CssScalarFieldEnum[]
}

/**
 * Css create
 */
export type CssCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Css
   */
  select?: Prisma.CssSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Css
   */
  omit?: Prisma.CssOmit<ExtArgs> | null
  /**
   * The data needed to create a Css.
   */
  data: Prisma.XOR<Prisma.CssCreateInput, Prisma.CssUncheckedCreateInput>
}

/**
 * Css createMany
 */
export type CssCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Csses.
   */
  data: Prisma.CssCreateManyInput | Prisma.CssCreateManyInput[]
}

/**
 * Css createManyAndReturn
 */
export type CssCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Css
   */
  select?: Prisma.CssSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Css
   */
  omit?: Prisma.CssOmit<ExtArgs> | null
  /**
   * The data used to create many Csses.
   */
  data: Prisma.CssCreateManyInput | Prisma.CssCreateManyInput[]
}

/**
 * Css update
 */
export type CssUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Css
   */
  select?: Prisma.CssSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Css
   */
  omit?: Prisma.CssOmit<ExtArgs> | null
  /**
   * The data needed to update a Css.
   */
  data: Prisma.XOR<Prisma.CssUpdateInput, Prisma.CssUncheckedUpdateInput>
  /**
   * Choose, which Css to update.
   */
  where: Prisma.CssWhereUniqueInput
}

/**
 * Css updateMany
 */
export type CssUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Csses.
   */
  data: Prisma.XOR<Prisma.CssUpdateManyMutationInput, Prisma.CssUncheckedUpdateManyInput>
  /**
   * Filter which Csses to update
   */
  where?: Prisma.CssWhereInput
  /**
   * Limit how many Csses to update.
   */
  limit?: number
}

/**
 * Css updateManyAndReturn
 */
export type CssUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Css
   */
  select?: Prisma.CssSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Css
   */
  omit?: Prisma.CssOmit<ExtArgs> | null
  /**
   * The data used to update Csses.
   */
  data: Prisma.XOR<Prisma.CssUpdateManyMutationInput, Prisma.CssUncheckedUpdateManyInput>
  /**
   * Filter which Csses to update
   */
  where?: Prisma.CssWhereInput
  /**
   * Limit how many Csses to update.
   */
  limit?: number
}

/**
 * Css upsert
 */
export type CssUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Css
   */
  select?: Prisma.CssSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Css
   */
  omit?: Prisma.CssOmit<ExtArgs> | null
  /**
   * The filter to search for the Css to update in case it exists.
   */
  where: Prisma.CssWhereUniqueInput
  /**
   * In case the Css found by the `where` argument doesn't exist, create a new Css with this data.
   */
  create: Prisma.XOR<Prisma.CssCreateInput, Prisma.CssUncheckedCreateInput>
  /**
   * In case the Css was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CssUpdateInput, Prisma.CssUncheckedUpdateInput>
}

/**
 * Css delete
 */
export type CssDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Css
   */
  select?: Prisma.CssSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Css
   */
  omit?: Prisma.CssOmit<ExtArgs> | null
  /**
   * Filter which Css to delete.
   */
  where: Prisma.CssWhereUniqueInput
}

/**
 * Css deleteMany
 */
export type CssDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Csses to delete
   */
  where?: Prisma.CssWhereInput
  /**
   * Limit how many Csses to delete.
   */
  limit?: number
}

/**
 * Css without action
 */
export type CssDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Css
   */
  select?: Prisma.CssSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Css
   */
  omit?: Prisma.CssOmit<ExtArgs> | null
}
