
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Html` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Html
 * 
 */
export type HtmlModel = runtime.Types.Result.DefaultSelection<Prisma.$HtmlPayload>

export type AggregateHtml = {
  _count: HtmlCountAggregateOutputType | null
  _avg: HtmlAvgAggregateOutputType | null
  _sum: HtmlSumAggregateOutputType | null
  _min: HtmlMinAggregateOutputType | null
  _max: HtmlMaxAggregateOutputType | null
}

export type HtmlAvgAggregateOutputType = {
  id: number | null
}

export type HtmlSumAggregateOutputType = {
  id: number | null
}

export type HtmlMinAggregateOutputType = {
  id: number | null
  key: string | null
  content: string | null
}

export type HtmlMaxAggregateOutputType = {
  id: number | null
  key: string | null
  content: string | null
}

export type HtmlCountAggregateOutputType = {
  id: number
  key: number
  content: number
  _all: number
}


export type HtmlAvgAggregateInputType = {
  id?: true
}

export type HtmlSumAggregateInputType = {
  id?: true
}

export type HtmlMinAggregateInputType = {
  id?: true
  key?: true
  content?: true
}

export type HtmlMaxAggregateInputType = {
  id?: true
  key?: true
  content?: true
}

export type HtmlCountAggregateInputType = {
  id?: true
  key?: true
  content?: true
  _all?: true
}

export type HtmlAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Html to aggregate.
   */
  where?: Prisma.HtmlWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Htmls to fetch.
   */
  orderBy?: Prisma.HtmlOrderByWithRelationInput | Prisma.HtmlOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.HtmlWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Htmls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Htmls.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Htmls
  **/
  _count?: true | HtmlCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: HtmlAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: HtmlSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: HtmlMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: HtmlMaxAggregateInputType
}

export type GetHtmlAggregateType<T extends HtmlAggregateArgs> = {
      [P in keyof T & keyof AggregateHtml]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateHtml[P]>
    : Prisma.GetScalarType<T[P], AggregateHtml[P]>
}




export type HtmlGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.HtmlWhereInput
  orderBy?: Prisma.HtmlOrderByWithAggregationInput | Prisma.HtmlOrderByWithAggregationInput[]
  by: Prisma.HtmlScalarFieldEnum[] | Prisma.HtmlScalarFieldEnum
  having?: Prisma.HtmlScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: HtmlCountAggregateInputType | true
  _avg?: HtmlAvgAggregateInputType
  _sum?: HtmlSumAggregateInputType
  _min?: HtmlMinAggregateInputType
  _max?: HtmlMaxAggregateInputType
}

export type HtmlGroupByOutputType = {
  id: number
  key: string
  content: string
  _count: HtmlCountAggregateOutputType | null
  _avg: HtmlAvgAggregateOutputType | null
  _sum: HtmlSumAggregateOutputType | null
  _min: HtmlMinAggregateOutputType | null
  _max: HtmlMaxAggregateOutputType | null
}

type GetHtmlGroupByPayload<T extends HtmlGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<HtmlGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof HtmlGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], HtmlGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], HtmlGroupByOutputType[P]>
      }
    >
  >



export type HtmlWhereInput = {
  AND?: Prisma.HtmlWhereInput | Prisma.HtmlWhereInput[]
  OR?: Prisma.HtmlWhereInput[]
  NOT?: Prisma.HtmlWhereInput | Prisma.HtmlWhereInput[]
  id?: Prisma.IntFilter<"Html"> | number
  key?: Prisma.StringFilter<"Html"> | string
  content?: Prisma.StringFilter<"Html"> | string
}

export type HtmlOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  content?: Prisma.SortOrder
}

export type HtmlWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  key?: string
  AND?: Prisma.HtmlWhereInput | Prisma.HtmlWhereInput[]
  OR?: Prisma.HtmlWhereInput[]
  NOT?: Prisma.HtmlWhereInput | Prisma.HtmlWhereInput[]
  content?: Prisma.StringFilter<"Html"> | string
}, "id" | "key">

export type HtmlOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  content?: Prisma.SortOrder
  _count?: Prisma.HtmlCountOrderByAggregateInput
  _avg?: Prisma.HtmlAvgOrderByAggregateInput
  _max?: Prisma.HtmlMaxOrderByAggregateInput
  _min?: Prisma.HtmlMinOrderByAggregateInput
  _sum?: Prisma.HtmlSumOrderByAggregateInput
}

export type HtmlScalarWhereWithAggregatesInput = {
  AND?: Prisma.HtmlScalarWhereWithAggregatesInput | Prisma.HtmlScalarWhereWithAggregatesInput[]
  OR?: Prisma.HtmlScalarWhereWithAggregatesInput[]
  NOT?: Prisma.HtmlScalarWhereWithAggregatesInput | Prisma.HtmlScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Html"> | number
  key?: Prisma.StringWithAggregatesFilter<"Html"> | string
  content?: Prisma.StringWithAggregatesFilter<"Html"> | string
}

export type HtmlCreateInput = {
  key: string
  content: string
}

export type HtmlUncheckedCreateInput = {
  id?: number
  key: string
  content: string
}

export type HtmlUpdateInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
}

export type HtmlUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  key?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
}

export type HtmlCreateManyInput = {
  id?: number
  key: string
  content: string
}

export type HtmlUpdateManyMutationInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
}

export type HtmlUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  key?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
}

export type HtmlCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  content?: Prisma.SortOrder
}

export type HtmlAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type HtmlMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  content?: Prisma.SortOrder
}

export type HtmlMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  content?: Prisma.SortOrder
}

export type HtmlSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type HtmlSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  key?: boolean
  content?: boolean
}, ExtArgs["result"]["html"]>

export type HtmlSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  key?: boolean
  content?: boolean
}, ExtArgs["result"]["html"]>

export type HtmlSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  key?: boolean
  content?: boolean
}, ExtArgs["result"]["html"]>

export type HtmlSelectScalar = {
  id?: boolean
  key?: boolean
  content?: boolean
}

export type HtmlOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "key" | "content", ExtArgs["result"]["html"]>

export type $HtmlPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Html"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    key: string
    content: string
  }, ExtArgs["result"]["html"]>
  composites: {}
}

export type HtmlGetPayload<S extends boolean | null | undefined | HtmlDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$HtmlPayload, S>

export type HtmlCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<HtmlFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: HtmlCountAggregateInputType | true
  }

export interface HtmlDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Html'], meta: { name: 'Html' } }
  /**
   * Find zero or one Html that matches the filter.
   * @param {HtmlFindUniqueArgs} args - Arguments to find a Html
   * @example
   * // Get one Html
   * const html = await prisma.html.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends HtmlFindUniqueArgs>(args: Prisma.SelectSubset<T, HtmlFindUniqueArgs<ExtArgs>>): Prisma.Prisma__HtmlClient<runtime.Types.Result.GetResult<Prisma.$HtmlPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Html that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {HtmlFindUniqueOrThrowArgs} args - Arguments to find a Html
   * @example
   * // Get one Html
   * const html = await prisma.html.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends HtmlFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, HtmlFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__HtmlClient<runtime.Types.Result.GetResult<Prisma.$HtmlPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Html that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HtmlFindFirstArgs} args - Arguments to find a Html
   * @example
   * // Get one Html
   * const html = await prisma.html.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends HtmlFindFirstArgs>(args?: Prisma.SelectSubset<T, HtmlFindFirstArgs<ExtArgs>>): Prisma.Prisma__HtmlClient<runtime.Types.Result.GetResult<Prisma.$HtmlPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Html that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HtmlFindFirstOrThrowArgs} args - Arguments to find a Html
   * @example
   * // Get one Html
   * const html = await prisma.html.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends HtmlFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, HtmlFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__HtmlClient<runtime.Types.Result.GetResult<Prisma.$HtmlPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Htmls that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HtmlFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Htmls
   * const htmls = await prisma.html.findMany()
   * 
   * // Get first 10 Htmls
   * const htmls = await prisma.html.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const htmlWithIdOnly = await prisma.html.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends HtmlFindManyArgs>(args?: Prisma.SelectSubset<T, HtmlFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HtmlPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Html.
   * @param {HtmlCreateArgs} args - Arguments to create a Html.
   * @example
   * // Create one Html
   * const Html = await prisma.html.create({
   *   data: {
   *     // ... data to create a Html
   *   }
   * })
   * 
   */
  create<T extends HtmlCreateArgs>(args: Prisma.SelectSubset<T, HtmlCreateArgs<ExtArgs>>): Prisma.Prisma__HtmlClient<runtime.Types.Result.GetResult<Prisma.$HtmlPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Htmls.
   * @param {HtmlCreateManyArgs} args - Arguments to create many Htmls.
   * @example
   * // Create many Htmls
   * const html = await prisma.html.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends HtmlCreateManyArgs>(args?: Prisma.SelectSubset<T, HtmlCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Htmls and returns the data saved in the database.
   * @param {HtmlCreateManyAndReturnArgs} args - Arguments to create many Htmls.
   * @example
   * // Create many Htmls
   * const html = await prisma.html.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Htmls and only return the `id`
   * const htmlWithIdOnly = await prisma.html.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends HtmlCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, HtmlCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HtmlPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Html.
   * @param {HtmlDeleteArgs} args - Arguments to delete one Html.
   * @example
   * // Delete one Html
   * const Html = await prisma.html.delete({
   *   where: {
   *     // ... filter to delete one Html
   *   }
   * })
   * 
   */
  delete<T extends HtmlDeleteArgs>(args: Prisma.SelectSubset<T, HtmlDeleteArgs<ExtArgs>>): Prisma.Prisma__HtmlClient<runtime.Types.Result.GetResult<Prisma.$HtmlPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Html.
   * @param {HtmlUpdateArgs} args - Arguments to update one Html.
   * @example
   * // Update one Html
   * const html = await prisma.html.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends HtmlUpdateArgs>(args: Prisma.SelectSubset<T, HtmlUpdateArgs<ExtArgs>>): Prisma.Prisma__HtmlClient<runtime.Types.Result.GetResult<Prisma.$HtmlPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Htmls.
   * @param {HtmlDeleteManyArgs} args - Arguments to filter Htmls to delete.
   * @example
   * // Delete a few Htmls
   * const { count } = await prisma.html.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends HtmlDeleteManyArgs>(args?: Prisma.SelectSubset<T, HtmlDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Htmls.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HtmlUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Htmls
   * const html = await prisma.html.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends HtmlUpdateManyArgs>(args: Prisma.SelectSubset<T, HtmlUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Htmls and returns the data updated in the database.
   * @param {HtmlUpdateManyAndReturnArgs} args - Arguments to update many Htmls.
   * @example
   * // Update many Htmls
   * const html = await prisma.html.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Htmls and only return the `id`
   * const htmlWithIdOnly = await prisma.html.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends HtmlUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, HtmlUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HtmlPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Html.
   * @param {HtmlUpsertArgs} args - Arguments to update or create a Html.
   * @example
   * // Update or create a Html
   * const html = await prisma.html.upsert({
   *   create: {
   *     // ... data to create a Html
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Html we want to update
   *   }
   * })
   */
  upsert<T extends HtmlUpsertArgs>(args: Prisma.SelectSubset<T, HtmlUpsertArgs<ExtArgs>>): Prisma.Prisma__HtmlClient<runtime.Types.Result.GetResult<Prisma.$HtmlPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Htmls.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HtmlCountArgs} args - Arguments to filter Htmls to count.
   * @example
   * // Count the number of Htmls
   * const count = await prisma.html.count({
   *   where: {
   *     // ... the filter for the Htmls we want to count
   *   }
   * })
  **/
  count<T extends HtmlCountArgs>(
    args?: Prisma.Subset<T, HtmlCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], HtmlCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Html.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HtmlAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends HtmlAggregateArgs>(args: Prisma.Subset<T, HtmlAggregateArgs>): Prisma.PrismaPromise<GetHtmlAggregateType<T>>

  /**
   * Group by Html.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HtmlGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends HtmlGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: HtmlGroupByArgs['orderBy'] }
      : { orderBy?: HtmlGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, HtmlGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetHtmlGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Html model
 */
readonly fields: HtmlFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Html.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__HtmlClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Html model
 */
export interface HtmlFieldRefs {
  readonly id: Prisma.FieldRef<"Html", 'Int'>
  readonly key: Prisma.FieldRef<"Html", 'String'>
  readonly content: Prisma.FieldRef<"Html", 'String'>
}
    

// Custom InputTypes
/**
 * Html findUnique
 */
export type HtmlFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Html
   */
  select?: Prisma.HtmlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Html
   */
  omit?: Prisma.HtmlOmit<ExtArgs> | null
  /**
   * Filter, which Html to fetch.
   */
  where: Prisma.HtmlWhereUniqueInput
}

/**
 * Html findUniqueOrThrow
 */
export type HtmlFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Html
   */
  select?: Prisma.HtmlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Html
   */
  omit?: Prisma.HtmlOmit<ExtArgs> | null
  /**
   * Filter, which Html to fetch.
   */
  where: Prisma.HtmlWhereUniqueInput
}

/**
 * Html findFirst
 */
export type HtmlFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Html
   */
  select?: Prisma.HtmlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Html
   */
  omit?: Prisma.HtmlOmit<ExtArgs> | null
  /**
   * Filter, which Html to fetch.
   */
  where?: Prisma.HtmlWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Htmls to fetch.
   */
  orderBy?: Prisma.HtmlOrderByWithRelationInput | Prisma.HtmlOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Htmls.
   */
  cursor?: Prisma.HtmlWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Htmls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Htmls.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Htmls.
   */
  distinct?: Prisma.HtmlScalarFieldEnum | Prisma.HtmlScalarFieldEnum[]
}

/**
 * Html findFirstOrThrow
 */
export type HtmlFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Html
   */
  select?: Prisma.HtmlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Html
   */
  omit?: Prisma.HtmlOmit<ExtArgs> | null
  /**
   * Filter, which Html to fetch.
   */
  where?: Prisma.HtmlWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Htmls to fetch.
   */
  orderBy?: Prisma.HtmlOrderByWithRelationInput | Prisma.HtmlOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Htmls.
   */
  cursor?: Prisma.HtmlWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Htmls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Htmls.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Htmls.
   */
  distinct?: Prisma.HtmlScalarFieldEnum | Prisma.HtmlScalarFieldEnum[]
}

/**
 * Html findMany
 */
export type HtmlFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Html
   */
  select?: Prisma.HtmlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Html
   */
  omit?: Prisma.HtmlOmit<ExtArgs> | null
  /**
   * Filter, which Htmls to fetch.
   */
  where?: Prisma.HtmlWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Htmls to fetch.
   */
  orderBy?: Prisma.HtmlOrderByWithRelationInput | Prisma.HtmlOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Htmls.
   */
  cursor?: Prisma.HtmlWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Htmls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Htmls.
   */
  skip?: number
  distinct?: Prisma.HtmlScalarFieldEnum | Prisma.HtmlScalarFieldEnum[]
}

/**
 * Html create
 */
export type HtmlCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Html
   */
  select?: Prisma.HtmlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Html
   */
  omit?: Prisma.HtmlOmit<ExtArgs> | null
  /**
   * The data needed to create a Html.
   */
  data: Prisma.XOR<Prisma.HtmlCreateInput, Prisma.HtmlUncheckedCreateInput>
}

/**
 * Html createMany
 */
export type HtmlCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Htmls.
   */
  data: Prisma.HtmlCreateManyInput | Prisma.HtmlCreateManyInput[]
}

/**
 * Html createManyAndReturn
 */
export type HtmlCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Html
   */
  select?: Prisma.HtmlSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Html
   */
  omit?: Prisma.HtmlOmit<ExtArgs> | null
  /**
   * The data used to create many Htmls.
   */
  data: Prisma.HtmlCreateManyInput | Prisma.HtmlCreateManyInput[]
}

/**
 * Html update
 */
export type HtmlUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Html
   */
  select?: Prisma.HtmlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Html
   */
  omit?: Prisma.HtmlOmit<ExtArgs> | null
  /**
   * The data needed to update a Html.
   */
  data: Prisma.XOR<Prisma.HtmlUpdateInput, Prisma.HtmlUncheckedUpdateInput>
  /**
   * Choose, which Html to update.
   */
  where: Prisma.HtmlWhereUniqueInput
}

/**
 * Html updateMany
 */
export type HtmlUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Htmls.
   */
  data: Prisma.XOR<Prisma.HtmlUpdateManyMutationInput, Prisma.HtmlUncheckedUpdateManyInput>
  /**
   * Filter which Htmls to update
   */
  where?: Prisma.HtmlWhereInput
  /**
   * Limit how many Htmls to update.
   */
  limit?: number
}

/**
 * Html updateManyAndReturn
 */
export type HtmlUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Html
   */
  select?: Prisma.HtmlSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Html
   */
  omit?: Prisma.HtmlOmit<ExtArgs> | null
  /**
   * The data used to update Htmls.
   */
  data: Prisma.XOR<Prisma.HtmlUpdateManyMutationInput, Prisma.HtmlUncheckedUpdateManyInput>
  /**
   * Filter which Htmls to update
   */
  where?: Prisma.HtmlWhereInput
  /**
   * Limit how many Htmls to update.
   */
  limit?: number
}

/**
 * Html upsert
 */
export type HtmlUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Html
   */
  select?: Prisma.HtmlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Html
   */
  omit?: Prisma.HtmlOmit<ExtArgs> | null
  /**
   * The filter to search for the Html to update in case it exists.
   */
  where: Prisma.HtmlWhereUniqueInput
  /**
   * In case the Html found by the `where` argument doesn't exist, create a new Html with this data.
   */
  create: Prisma.XOR<Prisma.HtmlCreateInput, Prisma.HtmlUncheckedCreateInput>
  /**
   * In case the Html was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.HtmlUpdateInput, Prisma.HtmlUncheckedUpdateInput>
}

/**
 * Html delete
 */
export type HtmlDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Html
   */
  select?: Prisma.HtmlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Html
   */
  omit?: Prisma.HtmlOmit<ExtArgs> | null
  /**
   * Filter which Html to delete.
   */
  where: Prisma.HtmlWhereUniqueInput
}

/**
 * Html deleteMany
 */
export type HtmlDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Htmls to delete
   */
  where?: Prisma.HtmlWhereInput
  /**
   * Limit how many Htmls to delete.
   */
  limit?: number
}

/**
 * Html without action
 */
export type HtmlDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Html
   */
  select?: Prisma.HtmlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Html
   */
  omit?: Prisma.HtmlOmit<ExtArgs> | null
}
